### ISSUE TITLE
Add utility methods utilizing reified types

### ISSUE THREAD

**Issue by bram209** [micronaut-projects/micronaut-kotlin#49]
It is cumbersome to have to pass around Class objects in order to get generic types at runtime.

Kotlin solves this with reified types: https://kotlinlang.org/docs/reference/inline-functions.html

It would be nice if we could have utility methods that use reified types.

Example: 
```kotlin
inline fun <reified T> BlockingHttpClient.retrieve(uri: String) = retrieve(uri, T::class.java)
```

Now we can call 
```kotlin
val books : List<Book> = client.retrieve()
```
instead of 
```kotlin
val books : List<Book> = client.retrieve(Argument.listOf(Book::class.java))
```

Thoughts?

**Comment by damianw** [comment]
I often write these manually when they feel useful but indeed it would be nice to have them in a companion artifact. Unfortunately, adding adding them may add a non-trivial amount of overhead for maintainers since they need to be "in sync" whenever new APIs are added (or they'll just fall out of sync) and may not be worth it in general. Though I'm sure there's a core set of APIs that could be provided.

In particular, a function such as:
```Kotlin
inline fun <reified T> argumentOf() = object : GenericArgument<T>() {}
```
would be quite useful just by itself. (As a side note, your example does not capture the generic type - so you'd want something like this in that case.)

The issue becomes that framework must choose to either use `T::class.java` which doesn't capture the type, or something like `argumentOf` (or Kotlin's built-in `typeOf`) which incur some runtime overhead that doesn't happen with a `Class`. Either way, the framework chooses either give you a correctness footgun or a or performance footgun. Just having `argumentOf` might be a nice balance.

**Comment by graemerocher** [comment]
This seems related to https://github.com/micronaut-projects/micronaut-kotlin/pull/48 in a way

We are happy to have Kotlin users contribute to this area but would request someone from the Kotlin community to help review the changes.

In summary ... PRs welcome

**Comment by damianw** [comment]
Now that I look at it - `typeOf` doesn't have much overhead (though it does require kotlin-reflect) to convert to a java `Type`. Could probably implement a subclass of `Argument` that takes a KType or something.

**Comment by willbuck** [comment]
@bram209 @damianw can we work together to find five to ten "really commonly feel pain" functions here that you think would benefit from reified type inlines that we can start out with? I don't think we're planning to change method signatures on APIs very often, but I share @damianw's concern that I don't want this to become a maintenance burden in the name of convenience.

**Comment by willbuck** [comment]
@jameskleeh also brought to my attention this project for useful reified extension functions for micronaut: https://github.com/ideaplugins/micronaut-ktx Thanks James!

I will reach out to @ideaplugins to see if there's an opportunity to PR some of the good work done in the above repo into an official module, but in the meantime it looks like something promising!

**Comment by ideaplugins** [comment]
Hi @willbuck , unfortunately, I don't have time to work on this righ now. But if anyone else wants to grab my code and move it to an official module, please feel free to do it

**Comment by willbuck** [comment]
@ideaplugins that is totally understandable, thank you for checking in! Would you have just a few moments to review the Contributor's License Agreement and sign it so that I am able to pull in some of the good work you've done? You can find it here: https://cla-assistant.io/micronaut-projects/micronaut-kotlin

Thanks very much for being a part of our community!

**Comment by ideaplugins** [comment]
@willbuck signed

**Comment by willbuck** [comment]
thanks very much @ideaplugins! I'll get to porting

**Comment by morki** [comment]
@bram209 you can close, merged in https://github.com/micronaut-projects/micronaut-kotlin/pull/53 :)

**Comment by bram209** [comment]
Sorry for the late reply, have been really busy.
Sorry that I couldn't review it as well, but glad it got merged, thanks all!
